"""End-to-end Step 2 entry point: benchmark, train + save production artifacts, write report.

Usage: uv run python scripts/train_fraud.py [--skip-benchmark] [--models catboost lightgbm ...]
"""

import argparse
import time
from collections.abc import Sequence
from pathlib import Path

import pandas as pd

from autoclaim.config import load_carrier_config
from autoclaim.core.rules import RuleSet
from autoclaim.datasets import vehicle_fraud
from autoclaim.datasets.download import read_manifest
from autoclaim.datasets.profile import to_markdown
from autoclaim.datasets.sources import VEHICLE_FRAUD
from autoclaim.lines.auto.fraud_tools import RULES_PATH
from autoclaim.ml import fraud_model
from autoclaim.ml.benchmark import run_benchmark
from autoclaim.ml.features import TARGET, clean
from autoclaim.ml.models import MODELS
from autoclaim.ml.split import time_split


def _metrics_table(metadata: dict[str, object]) -> pd.DataFrame:
    test_metrics = metadata["test_metrics"]
    assert isinstance(test_metrics, dict)
    return pd.DataFrame(test_metrics).T.round(4)


def feature_importance(artifacts: fraud_model.FraudArtifacts, top: int = 15) -> pd.DataFrame:
    imp = artifacts.model.get_feature_importance()  # PredictionValuesChange, sums to 100
    frame = pd.DataFrame({"importance": imp}, index=pd.Index(artifacts.features, name="feature"))
    return frame.sort_values("importance", ascending=False).head(top).round(2)


def render(
    benchmark: pd.DataFrame | None,
    artifacts: fraud_model.FraudArtifacts,
    rules_all: pd.DataFrame,
    rules_test: pd.DataFrame,
) -> str:
    md = artifacts.metadata
    parts = [
        "# Fraud model benchmark",
        "",
        "_Auto-generated by `scripts/train_fraud.py`. Interpretation: `docs/model_card.md`._",
        "",
        f"Time split: train {md['train_years']} ({md['n_train']:,} claims), "
        f"test {md['test_years']} ({md['n_test']:,} claims). "
        f"Review budget: top {md['review_budget']:.0%} of claims by score. "
        f"Sensitive features excluded: {md['excluded_sensitive_features']}.",
    ]
    if benchmark is not None:
        parts += ["", "## Model comparison", to_markdown(benchmark, "model")]
    parts += [
        "",
        f"## Production artifacts (`{artifacts.version}`), scored on the test years",
        f"CatBoost refit on all training years with {md['n_trees']} trees "
        "(tree count chosen by early stopping on the latest 20% of the training period).",
        "",
        to_markdown(_metrics_table(md), "signal"),
        "",
        "## Global feature importance (CatBoost, top 15)",
        to_markdown(feature_importance(artifacts), "feature"),
        "",
        "## Red-flag rules on labeled data",
        "All years (rules are hand-written, not trained, so there is no leakage):",
        "",
        to_markdown(rules_all, "rule"),
        "",
        "Test years only:",
        "",
        to_markdown(rules_test, "rule"),
        "",
    ]
    return "\n".join(parts)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Benchmark and train the fraud model.")
    parser.add_argument("--skip-benchmark", action="store_true")
    parser.add_argument("--models", nargs="*", default=list(MODELS))
    parser.add_argument("--report", type=Path, default=Path("docs/fraud_benchmark.md"))
    parser.add_argument("--model-dir", type=Path, default=None)
    parser.add_argument("--csv", type=Path, default=None)
    args = parser.parse_args(argv)
    unknown = sorted(set(args.models) - set(MODELS))
    if unknown:
        parser.error(f"unknown model(s) {unknown}; choose from {sorted(MODELS)}")

    config = load_carrier_config()
    cfg, seed = config.fraud_model, config.harness.seed
    raw, _ = vehicle_fraud.load_validated(args.csv)
    df = clean(raw)
    manifest = read_manifest(vehicle_fraud.csv_path().parent) if args.csv is None else None
    data_sha = manifest.files.get(VEHICLE_FRAUD.files[0]) if manifest else None

    benchmark = None
    if not args.skip_benchmark:
        start = time.perf_counter()
        benchmark = run_benchmark(df, cfg, seed, models=args.models)
        print(f"benchmark done in {time.perf_counter() - start:.0f}s")
        print(benchmark.to_string())

    artifacts = fraud_model.train_final(df, cfg, seed, data_sha256=data_sha)
    out_dir = fraud_model.save(artifacts, args.model_dir)
    print(f"saved {artifacts.version} -> {out_dir}")

    rules = RuleSet.from_yaml(RULES_PATH)
    _, test = time_split(df, cfg.train_years, cfg.test_years)
    report = render(benchmark, artifacts, rules.report(df, TARGET), rules.report(test, TARGET))
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(report, encoding="utf-8")
    print(f"report -> {args.report}")
    return 0
