"""Fraud-model entry point: canaries -> benchmark -> production artifacts -> report.

Usage:
  uv run python scripts/train_fraud.py                      # production dataset, validation only
  uv run python scripts/train_fraud.py --dataset legacy_1990s
  uv run python scripts/train_fraud.py --final              # also the locked test set + holdouts
                                                            # (logged in docs/test_set_log.md)
"""

import argparse
import time
from collections.abc import Sequence
from pathlib import Path

import pandas as pd

from autoclaim.config import FraudModelConfig, load_carrier_config
from autoclaim.core.rules import RuleSet
from autoclaim.datasets.profile import to_markdown
from autoclaim.lines.auto.datasets import get_spec
from autoclaim.lines.auto.fraud_tools import RULES_PATH
from autoclaim.ml import fraud_model, test_log
from autoclaim.ml.benchmark import Benchmark, run_benchmark
from autoclaim.ml.canaries import CanaryReport, run_canaries
from autoclaim.ml.frame import Y, feature_list
from autoclaim.ml.models import MODELS
from autoclaim.ml.spec import DatasetSpec


def feature_importance(artifacts: fraud_model.FraudArtifacts, top: int = 15) -> pd.DataFrame:
    imp = artifacts.model.get_feature_importance()  # PredictionValuesChange, sums to 100
    frame = pd.DataFrame({"importance": imp}, index=pd.Index(artifacts.features, name="feature"))
    return frame.sort_values("importance", ascending=False).head(top).round(2)


def rules_report(spec: DatasetSpec, raw: pd.DataFrame, frame: pd.DataFrame) -> pd.DataFrame:
    rules = RuleSet.from_yaml(RULES_PATH)
    canonical = spec.canonical(raw).assign(**{Y: frame[Y]})
    report = rules.report(canonical, Y)
    unchecked = rules.unchecked(canonical).mean()
    report["unchecked_share"] = unchecked.round(3)
    return report


def holdout_metrics(
    spec: DatasetSpec, artifacts: fraud_model.FraudArtifacts, cfg: FraudModelConfig
) -> pd.DataFrame:
    if spec.load_holdouts is None:
        return pd.DataFrame()
    rows = []
    for name, raw in spec.load_holdouts().items():
        metrics = artifacts.test_metrics(spec.prepare(raw), cfg.review_budget)["catboost"]
        rows.append({"holdout": name, **{k: round(v, 4) for k, v in metrics.items()}})
    return pd.DataFrame(rows).set_index("holdout")


def render(
    spec: DatasetSpec,
    frame: pd.DataFrame,
    canaries: CanaryReport,
    bench: Benchmark | None,
    artifacts: fraud_model.FraudArtifacts,
    rules: pd.DataFrame,
    holdouts: pd.DataFrame | None,
    cfg: FraudModelConfig,
) -> str:
    train, val, test = spec.split(frame)
    md = artifacts.metadata
    parts = [
        f"# Fraud benchmark: `{spec.name}`",
        "",
        f"_{spec.description}. Auto-generated by `scripts/train_fraud.py`; "
        "interpretation in `docs/model_card.md`._",
        "",
        f"Splits (time-ordered): train {len(train):,} / validation {len(val):,} / "
        f"locked test {len(test):,}. Fraud rate {frame[Y].mean():.2%}. "
        f"Review budget top {cfg.review_budget:.0%}. Seeds {cfg.seeds}. "
        f"Excluded sensitive features: {list(spec.sensitive) or 'none'}.",
        "",
        "## Leakage canaries (train -> validation)",
        f"- Shuffled-label ROC-AUC, mean of {len(canaries.shuffled_aucs)} permutations: "
        f"**{canaries.shuffled_auc}** (runs {canaries.shuffled_aucs}; allowed: chance + "
        f"{canaries.shuffled_tolerance}) -> {'PASS' if canaries.shuffled_ok else 'FAIL'}",
        "- Strongest single features (ROC-AUC alone, flag > 0.9): "
        f"{canaries.top_single_feature_auc}"
        f" -> {'PASS' if not canaries.flagged else 'FAIL: ' + ', '.join(canaries.flagged)}",
    ]
    if bench is not None:
        parts += ["", "## Model comparison: validation (all decisions are made here)",
                  to_markdown(bench.validation, "model")]  # fmt: skip
        if bench.test is not None:
            parts += ["", "## Locked test set (`--final`; logged in docs/test_set_log.md)",
                      to_markdown(bench.test, "model")]  # fmt: skip
    saved = artifacts.version != "unversioned"
    title = f"`{artifacts.version}`" if saved else "not saved: reality-check dataset"
    parts += [
        "",
        f"## Production artifacts ({title})",
        f"CatBoost refit on train+validation ({md['n_fit']:,} claims) with {md['n_trees']} trees.",
    ]
    if md.get("test_metrics"):
        parts += ["", to_markdown(pd.DataFrame(md["test_metrics"]).T.round(4), "signal")]
    if holdouts is not None and not holdouts.empty:
        parts += ["", "## Holdouts (fresh seed; perturbed world = shift test)",
                  to_markdown(holdouts, "holdout")]  # fmt: skip
    parts += [
        "",
        "## Global feature importance (CatBoost, top 15)",
        to_markdown(feature_importance(artifacts), "feature"),
        "",
        "## Red-flag rules on this dataset's labels (train + validation)",
        to_markdown(rules, "rule"),
        "",
    ]
    return "\n".join(parts)


def main(argv: Sequence[str] | None = None) -> int:
    cfg = load_carrier_config().fraud_model
    parser = argparse.ArgumentParser(description="Benchmark and train the fraud model.")
    parser.add_argument("--dataset", default=cfg.production_dataset, choices=sorted(cfg.datasets))
    parser.add_argument("--models", nargs="*", default=list(MODELS))
    parser.add_argument("--skip-benchmark", action="store_true")
    parser.add_argument("--final", action="store_true", help="also score the locked test set")
    parser.add_argument("--report", type=Path, default=None)
    parser.add_argument("--model-dir", type=Path, default=None)
    parser.add_argument("--no-save", action="store_true")
    args = parser.parse_args(argv)
    unknown = sorted(set(args.models) - set(MODELS))
    if unknown:
        parser.error(f"unknown model(s) {unknown}; choose from {sorted(MODELS)}")

    spec = get_spec(args.dataset, cfg)
    raw = spec.load_raw()
    frame = spec.prepare(raw)
    train, val, _ = spec.split(frame)
    features = feature_list(frame, exclude=spec.sensitive)
    spec.check_features(features)
    canaries = run_canaries(train, val, features, seed=cfg.seeds[0])
    print(
        f"canaries OK: shuffled AUC {canaries.shuffled_auc}, "
        f"top single {canaries.top_single_feature_auc}"
    )

    bench = None
    if not args.skip_benchmark:
        start = time.perf_counter()
        bench = run_benchmark(frame, spec, cfg, models=args.models, final=args.final)
        print(f"benchmark done in {time.perf_counter() - start:.0f}s")
        print(bench.validation.to_string())

    artifacts = fraud_model.train_final(frame, spec, cfg, cfg.seeds[0], final=args.final)
    if args.dataset == cfg.production_dataset and not args.no_save:
        out_dir = fraud_model.save(artifacts, args.model_dir)  # assigns the version
        print(f"saved {artifacts.version} -> {out_dir}")

    holdouts = holdout_metrics(spec, artifacts, cfg) if args.final else None
    keep = frame.index.isin(pd.concat([train, val]).index)
    rules = rules_report(spec, raw[keep], frame[keep])
    report = render(spec, frame, canaries, bench, artifacts, rules, holdouts, cfg)
    path = args.report or Path(f"docs/fraud_benchmark_{spec.name}.md")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(report, encoding="utf-8")
    print(f"report -> {path}")

    if args.final:
        tm = artifacts.metadata["test_metrics"]["catboost"]
        test_log.append(
            spec.name,
            f"catboost test PR-AUC {tm['pr_auc']:.4f}, recall@{cfg.review_budget:.0%} "
            f"{tm['recall_at_budget']:.4f}",
        )
    return 0
