"""Brand assets for the UI: one palette, Lucide icons, self-made illustrations and animations.

Everything here is local (assets/, committed) except the demo photos (assets/demo_claims/,
regenerated by scripts/fetch_demo_images.py). Origins are listed in ASSETS.md.
"""

import base64
import html
import json
import re
from functools import lru_cache
from pathlib import Path
from typing import Any

from autoclaim.paths import REPO_ROOT

ASSETS = REPO_ROOT / "assets"
ICONS = ASSETS / "icons" / "lucide"
BRAND = ASSETS / "brand"
DEMO = ASSETS / "demo_claims"
PALETTE = {
    "navy": "#1e3a8a", "blue": "#2563eb", "sky": "#93c5fd", "mist": "#eef2ff",
    "mint": "#10b981", "amber": "#f59e0b", "coral": "#ef4444", "ink": "#1f2937",
    "paper": "#f6f7fb",
}  # fmt: skip
TONE_COLOR = {"ok": PALETTE["mint"], "warn": PALETTE["amber"], "bad": PALETTE["coral"]}


@lru_cache(maxsize=64)
def _icon_source(name: str) -> str:
    path = ICONS / f"{name}.svg"
    if not path.exists():
        raise KeyError(f"no Lucide icon {name!r} in {ICONS} (add it to scripts/fetch_icons.py)")
    return " ".join(path.read_text(encoding="utf-8").split())


def icon(name: str, size: int = 18, color: str = "currentColor", stroke: float = 2.0) -> str:
    """A Lucide icon as inline SVG (inherits the text colour unless `color` is given)."""
    svg = _icon_source(name)
    svg = re.sub(r'width="\d+"', f'width="{size}"', svg, count=1)
    svg = re.sub(r'height="\d+"', f'height="{size}"', svg, count=1)
    svg = svg.replace('stroke="currentColor"', f'stroke="{html.escape(color)}"', 1)
    svg = re.sub(r'stroke-width="[\d.]+"', f'stroke-width="{stroke:g}"', svg, count=1)
    return svg.replace("<svg ", '<svg class="lc" aria-hidden="true" ', 1)


def data_uri(path: Path) -> str:
    mime = "image/svg+xml" if path.suffix == ".svg" else f"image/{path.suffix.lstrip('.')}"
    return f"data:{mime};base64,{base64.b64encode(path.read_bytes()).decode()}"


def illustration(name: str, width: int = 260, alt: str = "") -> str:
    """A self-made illustration (assets/brand/<name>.svg) as an <img> tag."""
    return (f'<img src="{data_uri(BRAND / f"{name}.svg")}" width="{width}" '
            f'alt="{html.escape(alt or name)}" style="max-width:100%">')  # fmt: skip


# ---------------------------------------------------------------- animations (SVG + CSS)

ANIMATION_CSS = """
<style>
.lc {vertical-align: -3px; flex: none;}
@keyframes ac-spin {to {transform: rotate(360deg);}}
@keyframes ac-draw {from {stroke-dashoffset: var(--len);} to {stroke-dashoffset: 0;}}
@keyframes ac-pop {0% {transform: scale(.6); opacity: 0;} 70% {transform: scale(1.08); opacity: 1;}
                   100% {transform: scale(1);}}
@keyframes ac-pulse {0% {transform: scale(.9); opacity: .55;}
                     100% {transform: scale(1.7); opacity: 0;}}
@keyframes ac-breathe {0%, 100% {opacity: .45;} 50% {opacity: 1;}}
.ac-loader {display: flex; align-items: center; gap: 14px; padding: 14px 18px; background: #fff;
            border-radius: 14px; box-shadow: 0 1px 3px rgba(0,0,0,.06); color: #1f2937;}
.ac-loader .ring {animation: ac-spin 1.1s linear infinite; transform-origin: 50% 50%;}
.ac-loader .shield {animation: ac-breathe 1.6s ease-in-out infinite;}
.ac-loader small {display: block; color: #6b7280;}
.ac-tick {animation: ac-pop .45s ease-out both;}
.ac-tick .mark {--len: 40; stroke-dasharray: 40; animation: ac-draw .5s .25s ease-out both;}
.ac-alert {position: relative; display: inline-block; width: 44px; height: 44px;}
.ac-alert .halo {position: absolute; inset: 0; border-radius: 50%; background: #f59e0b;
                 animation: ac-pulse 1.6s ease-out infinite;}
.ac-alert svg {position: relative;}
@media (prefers-reduced-motion: reduce) {
  .ac-loader .ring, .ac-loader .shield, .ac-tick, .ac-tick .mark, .ac-alert .halo {animation: none;}
}
</style>
"""


def loader_html(title: str, detail: str = "") -> str:
    """Animated 'working' card: a spinning ring around a breathing shield."""
    return (
        '<div class="ac-loader" role="status" aria-live="polite">'
        '<svg width="40" height="40" viewBox="0 0 40 40" aria-hidden="true">'
        '<circle cx="20" cy="20" r="17" fill="none" stroke="#eef2ff" stroke-width="4"/>'
        '<circle class="ring" cx="20" cy="20" r="17" fill="none" stroke="#2563eb" '
        'stroke-width="4" stroke-linecap="round" stroke-dasharray="28 80"/>'
        '<path class="shield" d="M20 10 L28 13 V20 C28 25 24.5 28.5 20 30 C15.5 28.5 12 25 12 20 '
        'V13 Z" fill="#1e3a8a"/></svg>'
        f"<div><b>{html.escape(title)}</b><small>{html.escape(detail)}</small></div></div>"
    )


def success_tick(size: int = 44) -> str:
    """Animated success tick: a mint disc pops in, then the check draws itself."""
    return (f'<svg class="ac-tick" width="{size}" height="{size}" viewBox="0 0 44 44" '
            'aria-hidden="true"><circle cx="22" cy="22" r="20" fill="#ffffff"/>'
            '<path class="mark" d="M13 22.5 L19.5 29 L31.5 16" fill="none" stroke="#10b981" '
            'stroke-width="4.5" stroke-linecap="round" stroke-linejoin="round"/>'
            "</svg>")  # fmt: skip


def review_alert() -> str:
    """Animated review-needed alert: a pulsing halo behind a warning triangle."""
    return ('<span class="ac-alert" aria-hidden="true"><span class="halo"></span>'
            '<svg width="44" height="44" viewBox="0 0 44 44"><circle cx="22" cy="22" r="20" '
            'fill="#ffffff"/><path d="M22 11 L33 31 H11 Z" fill="#f59e0b" stroke="#f59e0b" '
            'stroke-width="2" stroke-linejoin="round"/><path d="M22 18 V25" stroke="#fff" '
            'stroke-width="3" stroke-linecap="round"/><circle cx="22" cy="28.4" r="1.6" '
            'fill="#fff"/></svg></span>')  # fmt: skip


def deny_mark() -> str:
    return ('<span style="display:inline-flex;width:44px;height:44px;border-radius:50%;'
            'background:#fff;align-items:center;justify-content:center">'
            f"{icon('circle-x', 30, PALETTE['coral'], 2.4)}</span>")  # fmt: skip


# ---------------------------------------------------------------- demo photos (Pexels/Unsplash API)


def demo_photos(folder: Path = DEMO) -> list[dict[str, Any]]:
    """Photos fetched by scripts/fetch_demo_images.py with their credit (photographer, links)."""
    meta = folder / "credits.json"
    if not meta.exists():
        return []
    rows: list[dict[str, Any]] = json.loads(meta.read_text(encoding="utf-8"))
    return [r for r in rows if r.get("url") or (r.get("file") and (folder / r["file"]).exists())]


def photo_src(photo: dict[str, Any], folder: Path = DEMO) -> str:
    """Hotlinked URL (Unsplash requires it) or the downloaded file inlined (Pexels)."""
    return str(photo["url"]) if photo.get("url") else data_uri(folder / str(photo["file"]))


def photo_for(key: int | str, photos: list[dict[str, Any]]) -> dict[str, Any] | None:
    """A stable photo per story (same story, same photo)."""
    if not photos:
        return None
    n = sum(map(ord, str(key))) if not isinstance(key, int) else key
    return photos[n % len(photos)]


def credit_html(photo: dict[str, Any]) -> str:
    """The provider's attribution line: 'Photo by <name> on <Pexels|Unsplash>', both linked."""
    who = html.escape(photo["photographer"])
    who_url, src_url = html.escape(photo["photographer_url"]), html.escape(photo["source_url"])
    where = html.escape(photo["provider"])
    return (f'Photo by <a href="{who_url}" target="_blank">{who}</a> on '
            f'<a href="{src_url}" target="_blank">{where}</a>')  # fmt: skip
